spring:
  r2dbc:
    url: r2dbc:mysql://192.168.31.211:33306/halo
    username: Dylan
    password: Dylan123456

  sql:
    init:
      mode: always
      platform: mysql

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
